Multi file, multi folder support
knqyf263/pet pull request #121
Opened 2019-12-12 19:03 UTC by helmecke

*Issue #47 , if available:*

*Description of changes:*
Added support for multiple files in multiple folders.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2019-12-23 09:26 UTC, knqyf263 commented
Thank you for the awesome contribution! Let me know why you removed config.go. Also, it would be appreciated if you show an example to use this new feature.

2020-01-07 09:42 UTC, helmecke commented
Thanks and sorry for the late reply.

> Let me know why you removed config.go.
`Viper` is very intuetive to work with and integrates nicely with `Cobra`. It removes the need to maintain an additional file which changes every time the config is changed.

> Also, it would be appreciated if you show an example to use this new feature.
I will add a section to the readme as soon as possible.

2020-01-20 13:12 UTC, helmecke commented
@knqyf263 I've added the Readme section. I would very much like your feedback.

2020-03-18 12:30 UTC, brandonkal commented
There's a typo in the readme change.

2020-09-08 06:40 UTC, knqyf263 commented
I'm so sorry to be too late. I'm reviewing this PR.

2020-09-08 06:49 UTC, knqyf263 requested changes
Could you revert config.go? If we don't have it, we have to access each value with a string like `viper.GetString("gitlab.file_name")` everywhere as you did. This is likely to cause typos and is not desirable for completion. If you strongly hope it, let's open the dedicated issue and discuss it.

2020-09-08 06:49 UTC, knqyf263 commented on Makefile
> -	test
Is there any reason to remove them?

2020-09-08 06:49 UTC, knqyf263 commented on cmd/clip.go
> +var clipCmd = &cobra.Command{
This feature is not related to multi-folder support, right? If so, could you open another PR for this feature?

2020-09-08 06:49 UTC, knqyf263 commented on cmd/completion.go
> +var completionCmd = &cobra.Command{
ditto

2020-09-08 11:30 UTC, helmecke commented
@knqyf263 it was my bad to open this PR from master branch. I'll try to cleanup this PR to only include multi-folder and multi-file support.

2020-09-13 06:07 UTC, closed without merging

2021-09-12 11:07 UTC, Piotr1215 commented
Hi everyone. Thank you for this great project! Is there any timeline on when this PR will be merged? I'm using @helmecke fork for now.