Add Git Sync Target
knqyf263/pet pull request #141
Opened 2020-08-31 18:06 UTC by hammerdr

This enables us to use a git repository and all of its
access to do a shared team repository for pet

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-08 06:39 UTC, knqyf263 requested changes
Many errors are not handled. Could you fix it? Also, would you write a document in README? We should make it clear what kind of setting we expect.

2020-09-08 06:39 UTC, knqyf263 commented on sync/git.go
> +	directory, err := getDirectory()
Handle error

2020-09-08 06:39 UTC, knqyf263 commented on sync/git.go
> +	r, err := getRepository(directory)
ditto

2020-09-08 06:39 UTC, knqyf263 commented on sync/git.go
> +	w, err := r.Worktree()
ditto

2020-09-08 06:39 UTC, knqyf263 commented on sync/git.go
> +	return "", errors.New("Git Directory not found")
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

```suggestion
	return "", errors.New("git directory not found")
```

2020-09-08 06:39 UTC, knqyf263 commented on sync/git.go
> +	return "", "", errors.New("Git Signature (Author, AuthorEmail) not found")
```suggestion
	return "", "", errors.New("git signature (Author, AuthorEmail) not found")
```

2020-09-08 06:39 UTC, knqyf263 commented on sync/git.go
> +			return nil, errors.Wrapf(err, "unable to create repository")
```suggestion
			return nil, fmt.Errorf("unable to create repository: %w", err)
```

2020-09-08 06:39 UTC, knqyf263 commented on sync/git.go
> +			return nil, errors.Wrapf(err, "unable to create repository")
From Go 1.13 onwards, we can wrap an error with `fmt.Errorf`

2020-09-08 06:39 UTC, knqyf263 commented on sync/sync.go
> +			return nil, errors.Wrap(err, "Failed to initialize GitLab client")
ditto

2020-09-16 01:32 UTC, pwen commented
+1 would be useful

2020-11-28 20:40 UTC, c33s commented
can't wait for git sync support

2022-08-05 19:46 UTC, closed without merging